name = "character-vault"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 生产环境（main 分支部署）
[[d1_databases]]
binding = "DB"
database_name = "character-vault-db"
database_id = "1f1da679-ca9d-4899-af0c-19f0e729f859"

# 预览环境（feature 分支部署）
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "character-vault-db-test"
database_id = "2c412cf6-cb44-4b43-95f3-bbba7cde3487"
